local M = {}

M.map = {
	['1'] = 'which_key_ignore',
	['2'] = 'which_key_ignore',
	['3'] = 'which_key_ignore',
	['4'] = 'which_key_ignore',
	['5'] = 'which_key_ignore',
	['6'] = 'which_key_ignore',
	['7'] = 'which_key_ignore',
	['8'] = 'which_key_ignore',
	['9'] = 'which_key_ignore',
	['<Tab>'] = 'file explorer',
	a = 'swap next function parameter',
	A = 'swap previous function parameter',
	d = {
		name = 'diffview',
		o = 'open',
		q = 'close',
		r = 'refresh',
	},
	f = {
		name = 'telescope',
		f = 'files',
		g = 'grep',
		h = 'history',
		l = 'lsp symbols',
		G = {
			name = 'git',
			g = 'commits',
			c = 'bcommits',
			b = 'branches',
			s = 'status',
		},
	},
	g = {
		name = 'lsp',
		c = 'peek definition code',
		d = 'definition',
		D = 'declaration',
		O = 'list definitions in table',
		h = 'info',
		i = 'implementation',
		l = 'list definitions',
		r = 'references',
		s = 'signature help',
	},
	G = 'neogit',
	h = {
		name = 'git signs',
		b = 'blame line',
		p = 'preview hunk',
		r = 'reset hunk',
		R = 'reset buffer',
		s = 'stage hunk',
		S = 'stage buffer',
		u = 'unstage hunk',
		U = 'unstage buffer',
	},
	n = {
		name = 'nvim-tree',
		r = 'refresh',
		f = 'find',
	},
	o = {
		name = 'orgmode',
		a = 'agenda',
		c = 'capture',
	},
	q = 'kill buffer',
	s = {
		name = 'saga',
		a = 'code actions',
		r = 'rename',
	},
	S = {
		name = 'session',
		s = 'save session',
		l = 'load session',
	},
	t = {
		name = 'dap',
		b = 'toggle breakpoint',
		B = 'set conditional breakpoint',
		c = 'debug c project',
		r = 'debug rust project',
	},
	x = {
		name = 'trouble',
		d = 'document',
		l = 'loclist',
		q = 'quickfix',
		t = 'todo',
		w = 'worskpace',
		x = 'toggle',
	},
}

M.prefix = '<Leader>'

return M
